version: '3.5'

services:
  k6-todo:
    depends_on:
      # k6-db is defined by an override
      k6-db:
        condition: service_healthy

    # Defined by override
    image: ""
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      # Defined by override
      DATABASE_URL: ""
